importWizard.label = Model From Architeezy Repository...
exportWizard.label = Model to Architeezy Repository...
openInBrowser.label = Open in Browser
openInBrowser.tooltip = Open the active model in a browser on the Architeezy server
pullModel.label = Pull from Architeezy
pullModel.tooltip = Save the active model and pull the latest version from the Architeezy server
pushModel.label = Push to Architeezy
pushModel.tooltip = Save the active model, pull remote updates (if any) and push local changes to the Architeezy server
toolbar.label = Architeezy
