importWizard.label = Model From Architeezy Repository...
exportWizard.label = Model to Architeezy Repository...
pullModel.label = Pull from Architeezy
pullModel.tooltip = Pull the latest version of the active model from the Architeezy server
pushModel.label = Push to Architeezy
pushModel.tooltip = Push local changes of the active model to the Architeezy server
toolbar.label = Architeezy
